# Generated by Django 5.1.8 on 2025-05-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_is_verified_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
