# Generated by Django 5.1.8 on 2025-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain_name',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
