# Generated by Django 5.1.8 on 2025-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_domain_name'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='source',
            name='tagged_companies',
        ),
        migrations.AddField(
            model_name='source',
            name='tagged_companies',
            field=models.ManyToManyField(to='company.company'),
        ),
    ]
