# Generated by Django 5.1.8 on 2025-05-08 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_domain_name'),
        ('source', '0003_source_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='company',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='userCompany', to='company.company'),
        ),
    ]
