# Generated by Django 5.1.8 on 2025-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_alter_source_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
