# Generated by Django 5.1.8 on 2025-05-29 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_domain_name'),
        ('source', '0009_alter_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('company', 'url'), name='unique_source_url'),
        ),
    ]
