# Generated by Django 5.1.8 on 2025-05-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='sources',
            new_name='source',
        ),
    ]
