# Generated by Django 5.1.8 on 2025-05-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_alter_source_company'),
        ('story', '0002_rename_sources_story_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.source'),
        ),
    ]
