# Generated by Django 5.1.8 on 2025-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
