# Generated by Django 5.1.8 on 2025-05-30 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_domain_name'),
        ('source', '0010_source_unique_source_url'),
        ('story', '0004_alter_story_title_alter_story_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storyCompany', to='company.company'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('company', 'url'), name='unique_story_url'),
        ),
    ]
