# Generated by Django 5.1.8 on 2025-05-30 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_domain_name'),
        ('source', '0010_source_unique_source_url'),
        ('story', '0005_story_company_story_unique_story_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='story',
            name='unique_story_url',
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('company', 'url'), name='unique_story_urls'),
        ),
    ]
