# Generated by Django 5.1.8 on 2025-06-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_remove_story_unique_story_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='published_date',
            field=models.DateField(),
        ),
    ]
